image: node
pipelines:
    default:
    - step:
       script:
          - apt-get -y update && apt-get -y install git
          - apt-get -qq install git-ftp
          - npm install -g cordova ionic
          - npm install
          - ionic build
          - cd www
          - ls
          - git ftp init --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.kombusovaca.com/public_html/gui
          - git ftp push --user $FTP_USERNAME --passwd $FTP_PASSWORD ftp://ftp.kombusovaca.com/public_html/gui